# app.yaml
# This file configures your Flutter web app for deployment to Google App Engine Standard environment.

runtime: nodejs20 # Using Node.js 20 runtime as requested
instance_class: F1 # F1 is a good default for static serving.
env: standard

handlers:
# Serve all static files from the 'build/web' directory.
# The 'build/web' directory is where 'flutter build web --release' places your compiled web app.
- url: /
  static_files: build/web/index.html
  upload: build/web/index.html
  # This serves index.html for the root URL.
  # For single-page applications like Flutter, you typically want all paths to resolve to index.html
  # so that the Flutter router can handle the client-side routing.

- url: /(.*)
  static_files: build/web/\1
  upload: build/web/(.*)
  # This handler serves all other static assets (JS, CSS, fonts, images) from the build/web directory.

# This final handler is crucial for Flutter's client-side routing.
# It ensures that any path not matching a static file is redirected to index.html,
# allowing the Flutter app to handle routing within the browser.
- url: /.*
  static_files: build/web/index.html
  upload: build/web/index.html
